on:
  push:
    tags:
      - "v*"
     
jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extension: ""
            name_suffix: linux
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            extension: ".exe"
            name_suffix: windows
          - os: macos-latest
            target: x86_64-apple-darwin
            extension: ""
            name_suffix: macos

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          # toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build the binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: test the binary
        run: cargo test --release --target ${{ matrix.target }}

      - name: rename binary for upload
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv target/${{ matrix.target }}/release/motif_methylation_state.exe motif_methylation_state-${{ matrix.name_suffix }}${{ matrix.extension }}
          else
            mv target/${{ matrix.target }}/release/motif_methylation_state motif_methylation_state-${{ matrix.name_suffix }}${{ matrix.extension }}
          fi
        shell: bash
        
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: motif_methylation_state-${{ matrix.name_suffix }}
          path: motif_methylation_state-${{ matrix.name_suffix }}${{ matrix.extension }}

  release:
    runs-on: ubuntu-latest
    needs: build-and-release

    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          pattern: motif_methylation_state-*
          merge-multiple: true
          run-id: ${{ github.event.workflow_run_id }}
      - name: Create github release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}  # Use the tag as the release version
          release_name: "Release ${{ github.ref_name }}"
          files: |
            methylation_utils-linux
            methylation_utils-windows.exe
            methylation_utils-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
